- name: OS family
  hosts: localhost

  tasks:
    - name: print OS Family
      debug: var=ansible_os_family
      debug: var=ansible_distribution
      debug: ansible_distribution_major_version
      debug: ansible_distribution_version
