- hosts: slave
  tasks:
    - name: Install add-apt-repo
      become: yes
      apt: name=software-properties-common state=latest
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: add oracle repo
      become: yes
      apt_repository: repo='ppa:webupd8team/java'
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Accept java 8 license
      become: yes
      debconf:  name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install Oracle java 8
      become: yes
      apt: name={{item}} state=latest
      with_items:
        - oracle-java8-installer
        - ca-certificates
        - oracle-java8-set-default
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
