- hosts: localhost
  tasks:
      -name: install httpd
       package:
         name: httpd
         state: present
      -name: copy html
         copy: src=/root/files/index.html dest=/var/www/html/index.html
      -name: start apache
       service:
           name: httpd
           state: restarted
